#define BLUETOOTH_DISCOVERY_TIMEOUT_SECONDS 1

#define BLUETOOTH_SERVICE_NAME "JSC Sample Bluetooth"
#define BLUETOOTH_SERVICE_DESCRIPTION "JSC Sample Bluetooth service"
#define BLUETOOTH_SERVICE_PROVIDER "JScoobyCed"
#define BLUETOOTH_SERVICE_CHANNEL 22

#define BLUETOOTH_SERVICE_PATH "/org/bluez/jscturret"
#define BLUETOOTH_SERVICE_UUID "12345678-1234-1234-1234-012345678901"